name: ltddnc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  google_nav_bar: ^5.0.6
  carousel_slider: ^4.2.1
  collection: ^1.18.0
  intl: ^0.19.0
  fl_chart: ^0.68.0
  dio: ^5.5.0+1
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  path: ^1.9.0
  image_picker: ^1.1.2
  file_picker: ^5.5.0
  sqflite: ^2.3.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts: 
    - family: BeVietnamPro
      fonts:
        - asset: assets/fonts/BeVietnamPro-Black.ttf
        - asset: assets/fonts/BeVietnamPro-BlackItalic.ttf
        - asset: assets/fonts/BeVietnamPro-Bold.ttf
        - asset: assets/fonts/BeVietnamPro-BoldItalic.ttf
        - asset: assets/fonts/BeVietnamPro-ExtraBold.ttf
        - asset: assets/fonts/BeVietnamPro-ExtraBoldItalic.ttf
        - asset: assets/fonts/BeVietnamPro-ExtraLight.ttf
        - asset: assets/fonts/BeVietnamPro-ExtraLightItalic.ttf
        - asset: assets/fonts/BeVietnamPro-Italic.ttf
        - asset: assets/fonts/BeVietnamPro-Light.ttf
        - asset: assets/fonts/BeVietnamPro-LightItalic.ttf
        - asset: assets/fonts/BeVietnamPro-Medium.ttf
        - asset: assets/fonts/BeVietnamPro-MediumItalic.ttf
        - asset: assets/fonts/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/BeVietnamPro-SemiBold.ttf
        - asset: assets/fonts/BeVietnamPro-SemiBoldItalic.ttf
        - asset: assets/fonts/BeVietnamPro-Thin.ttf
        - asset: assets/fonts/BeVietnamPro-ThinItalic.ttf

  assets:
    - assets/images/
    - assets/images/air/
    - assets/images/football/
    - assets/images/lifestyle/
    - assets/images/running/
    - assets/svg/
    - assets/fonts/
    - assets/files/
    - assets/icons/


